language: android
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-25"
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25
